### ISSUE TITLE
Select all from one alias does not work

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#129]
The following does not work:

```
select i.* from instances i
```

```
java.lang.IllegalArgumentException: Table "i" does not exist
        at org.meridor.perspective.sql.impl.table.TableName.fromString(TableName.java:45)
        at org.meridor.perspective.sql.impl.task.SelectTask.lambda$processSelectionMap$18(SelectTask.java:80)
        at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:555)
        at org.meridor.perspective.sql.impl.task.SelectTask.processSelectionMap(SelectTask.java:72)
        at org.meridor.perspective.sql.impl.task.SelectTask.init(SelectTask.java:42)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:219)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1069)
        at org.meridor.perspective.sql.impl.QuerySchedulerImpl.schedule(QuerySchedulerImpl.java:91)
        at org.meridor.perspective.sql.impl.QueryProcessorImpl.parseSQL(QueryProcessorImpl.java:58)
        at org.meridor.perspective.sql.impl.QueryProcessorImpl.process(QueryProcessorImpl.java:30)
        at org.meridor.perspective.rest.resources.QueryResource.lambda$query$8(QueryResource.java:37)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)

```

**Comment by vania-pooh** [comment]
Fixed with #102 (added test).
