### ISSUE TITLE
Memory leak in rest module

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#148]
Rest dies in one hour with 2 Gb of RAM.

```
2016-08-30 17:27:56,106 [      hz.client_0.event-3] ERROR com.hazelcast.client.spi.ClientListenerService               - hz.client_0 [perspective] [3.7] hz.client_0.event-3 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.ClientListenerServ
iceImpl$ClientEventProcessor@56afb93d
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
```

Need to check which objects grow. Seems to be related with indexes:

```
java.lang.OutOfMemoryError: Java heap space
        at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
        at java.util.HashMap.putVal(HashMap.java:630)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at org.meridor.perspective.sql.impl.index.impl.HashTableIndex$1.<init>(HashTableIndex.java:31)
        at org.meridor.perspective.sql.impl.index.impl.HashTableIndex.lambda$put$39(HashTableIndex.java:28)
        at org.meridor.perspective.sql.impl.index.impl.HashTableIndex$$Lambda$56/1563650573.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
        at org.meridor.perspective.sql.impl.index.impl.HashTableIndex.put(HashTableIndex.java:28)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl$$Lambda$25/728725375.apply(Unknown Source)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl.lambda$null$4(IndexerImpl.java:68)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl$$Lambda$51/189200606.apply(Unknown Source)
        at org.meridor.perspective.sql.impl.index.impl.IndexStorageImpl.update(IndexStorageImpl.java:42)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl.lambda$null$5(IndexerImpl.java:62)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl$$Lambda$50/1141233687.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl.lambda$forEachIndex$6(IndexerImpl.java:60)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl$$Lambda$44/797947812.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl.forEachIndex(IndexerImpl.java:58)
        at org.meridor.perspective.sql.impl.index.impl.IndexerImpl.add(IndexerImpl.java:39)
        at org.meridor.perspective.rest.data.listeners.BaseEntityListener.updateEntity(BaseEntityListener.java:26)
        at org.meridor.perspective.rest.data.listeners.ImagesListener.onEvent(ImagesListener.java:27)
        at org.meridor.perspective.rest.data.listeners.ImagesListener.onEvent(ImagesListener.java:14)
        at org.meridor.perspective.framework.storage.impl.StorageImpl$EntryListenerImpl.entryUpdated(StorageImpl.java:328)
        at com.hazelcast.map.impl.MapListenerAdaptors$4$1.onEvent(MapListenerAdaptors.java:128)
        at com.hazelcast.map.impl.MapListenerAdaptors$4$1.onEvent(MapListenerAdaptors.java:125)
        at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56)
        at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35)
        at com.hazelcast.client.proxy.ClientMapProxy$ClientMapEventHandler.handle(ClientMapProxy.java:1475)
        at com.hazelcast.client.impl.protocol.codec.MapAddEntryListenerCodec$AbstractEventHandler.handle(MapAddEntryListenerCodec.java:226)
```

**Comment by vania-pooh** [comment]
Seems to be fixed but waiting 24 hours with running REST to be sure.

**Comment by vania-pooh** [comment]
Fixed. Works now.
