### ISSUE TITLE
NPE in instance modification listener

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#154]
```
2016-09-11 16:57:57,713 [      hz.client_0.event-3] ERROR com.hazelcast.client.spi.ClientListenerService               - hz.client_0 [perspective] [3.7] hz.client_0.event-3 caught an exception while processing task:com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor@39b8434c
java.lang.NullPointerException
    at org.meridor.perspective.worker.fetcher.impl.InstanceModificationListener.getLastModifiedInstant(InstanceModificationListener.java:45)
    at org.meridor.perspective.worker.fetcher.impl.InstanceModificationListener.getLastModifiedInstant(InstanceModificationListener.java:14)
    at org.meridor.perspective.worker.fetcher.impl.LastModificationListener.getLastModified(LastModificationListener.java:87)
    at org.meridor.perspective.worker.fetcher.impl.LastModificationListener.onEvent(LastModificationListener.java:67)
    at org.meridor.perspective.framework.storage.impl.StorageImpl$EntryListenerImpl.entryEvicted(StorageImpl.java:305)
    at com.hazelcast.map.impl.MapListenerAdaptors$3$1.onEvent(MapListenerAdaptors.java:107)
    at com.hazelcast.map.impl.MapListenerAdaptors$3$1.onEvent(MapListenerAdaptors.java:104)
    at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:56)
    at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:35)
    at com.hazelcast.client.proxy.ClientMapProxy$ClientMapEventHandler.handle(ClientMapProxy.java:1475)
    at com.hazelcast.client.impl.protocol.codec.MapAddEntryListenerCodec$AbstractEventHandler.handle(MapAddEntryListenerCodec.java:226)
    at com.hazelcast.client.proxy.ClientMapProxy$ClientMapEventHandler.handle(ClientMapProxy.java:1459)
    at com.hazelcast.client.spi.impl.listener.ClientListenerServiceImpl$ClientEventProcessor.run(ClientListenerServiceImpl.java:124)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
```

**Comment by vania-pooh** [comment]
This is caused by instance eviction.
