### ISSUE TITLE
Issue with start instance command

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#168]
```
2016-10-15 12:34:24,289 [          pool-3-thread-1] DEBUG org.meridor.perspective.worker.processor.InstancesProcessor  - Updating instance test-instance (2e5dc842-ec59-319e-88b9-ac9b38fc6547) from state = InstanceLaunchingEvent to state = InstanceLaunchingEvent
2016-10-15 12:34:24,327 [          pool-3-thread-1] INFO  org.meridor.perspective.worker.processor.InstanceFSM         - Adding instance test-instance (2e5dc842-ec59-319e-88b9-ac9b38fc6547)
...

2016-10-15 12:34:28,864 [          pool-3-thread-1] ERROR org.meridor.perspective.openstack.AddInstanceOperation       - Failed to add instance test-instance
ClientResponseException{message=Instance test-instance already exists., status=409, status-code=CONFLICT}
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
    at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)

2016-10-15 12:34:33,306 [          pool-3-thread-2] ERROR org.meridor.perspective.openstack.AddInstanceOperation       - Failed to add instance test-instance
ClientResponseException{message=Instance test-instance already exists., status=409, status-code=CONFLICT}
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
    at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
    at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)
```

**Comment by vania-pooh** [comment]
Related to #115.
