### ISSUE TITLE
Exceptions while syncing instances in DigitalOcean

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#192]
```
2016-11-29 19:40:46,231 [readPoolTaskScheduler#0-2] ERROR org.meridor.perspective.digitalocean.ListInstancesOperation  - Failed to fetch instances with ids = [036dbfde-e5a6-48a3-9754-e62b81fff91c] for cloud = default
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.meridor.perspective.digitalocean.ListInstancesOperation.perform(ListInstancesOperation.java:70)
	at org.meridor.perspective.worker.operation.impl.OperationProcessorImpl.consumeImpl(OperationProcessorImpl.java:46)
	at org.meridor.perspective.worker.operation.impl.OperationProcessorImpl.consume(OperationProcessorImpl.java:36)
	at org.meridor.perspective.worker.fetcher.impl.InstancesFetcher.fetch(InstancesFetcher.java:70)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher.lambda$null$15(BaseFetcher.java:76)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher$$Lambda$13/1892865681.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher.lambda$scheduleIdsFetch$16(BaseFetcher.java:72)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher$$Lambda$12/1360533184.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-11-29 19:40:46,231 [readPoolTaskScheduler#0-2] ERROR org.meridor.perspective.worker.fetcher.impl.InstancesFetcher - Error while fetching instances with ids = [036dbfde-e5a6-48a3-9754-e62b81fff91c] for cloud = default
java.lang.RuntimeException: Failed to get instances with ids = [036dbfde-e5a6-48a3-9754-e62b81fff91c] from cloud = default
	at org.meridor.perspective.worker.fetcher.impl.InstancesFetcher.fetch(InstancesFetcher.java:71)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher.lambda$null$15(BaseFetcher.java:76)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher$$Lambda$13/1892865681.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher.lambda$scheduleIdsFetch$16(BaseFetcher.java:72)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher$$Lambda$12/1360533184.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vania-pooh** [comment]
Also:
```
java.lang.NullPointerException
	at org.meridor.perspective.digitalocean.ListInstancesOperation.addKeypairs(ListInstancesOperation.java:202)
	at org.meridor.perspective.digitalocean.ListInstancesOperation.processInstance(ListInstancesOperation.java:110)
	at org.meridor.perspective.digitalocean.ListInstancesOperation.lambda$perform$13(ListInstancesOperation.java:53)
	at org.meridor.perspective.digitalocean.ListInstancesOperation$$Lambda$24/1749588602.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.meridor.perspective.digitalocean.ListInstancesOperation.perform(ListInstancesOperation.java:53)
	at org.meridor.perspective.worker.operation.impl.OperationProcessorImpl.consumeImpl(OperationProcessorImpl.java:45)
	at org.meridor.perspective.worker.operation.impl.OperationProcessorImpl.consume(OperationProcessorImpl.java:31)
	at org.meridor.perspective.worker.fetcher.impl.InstancesFetcher.fetch(InstancesFetcher.java:57)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher$$Lambda$14/507583873.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher.lambda$forEachCloud$17(BaseFetcher.java:96)
	at org.meridor.perspective.worker.fetcher.impl.BaseFetcher$$Lambda$15/1404669942.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
