### ISSUE TITLE
Rebuild operation does not work for DO

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#196]
```
2016-12-03 21:21:48,914 [          pool-3-thread-2] ERROR org.meridor.perspective.digitalocean.BaseInstanceOperation   - Failed to rebuild instance test-instance-blr (255ae6aa-aa1f-3654-a20c-cbef8e846abd)
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "ce42bf56-5fd0-3d84-9e0c-ed6e03684cf4"
	at org.meridor.perspective.digitalocean.RebuildInstanceOperation.lambda$getAction$0(RebuildInstanceOperation.java:21)
	at org.meridor.perspective.digitalocean.RebuildInstanceOperation$$Lambda$53/929346240.apply(Unknown Source)
	at org.meridor.perspective.digitalocean.BaseInstanceOperation.perform(BaseInstanceOperation.java:30)
	at org.meridor.perspective.worker.operation.impl.OperationProcessorImpl.supply(OperationProcessorImpl.java:58)
	at org.meridor.perspective.worker.processor.InstanceFSM.onInstanceRebuilding(InstanceFSM.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.callMethod(BestMatchedAnnotatedMethodCaller.java:100)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.findSuitableMethodAndCall(BestMatchedAnnotatedMethodCaller.java:70)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.call(BestMatchedAnnotatedMethodCaller.java:51)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.call(BestMatchedAnnotatedMethodCaller.java:31)
	at ru.yandex.qatools.fsm.impl.YatomataImpl.fire(YatomataImpl.java:115)
	at org.meridor.perspective.worker.processor.InstancesProcessor.processInstances(InstancesProcessor.java:57)
	at org.meridor.perspective.worker.processor.InstancesProcessor.process(InstancesProcessor.java:37)
	at org.meridor.perspective.worker.processor.WorkerDispatcher.dispatch(WorkerDispatcher.java:45)
	at org.meridor.perspective.backend.messaging.impl.BaseConsumer.lambda$getRunnable$0(BaseConsumer.java:69)
	at org.meridor.perspective.backend.messaging.impl.BaseConsumer$$Lambda$21/1848886161.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "ce42bf56-5fd0-3d84-9e0c-ed6e03684cf4"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.meridor.perspective.digitalocean.RebuildInstanceOperation.lambda$getAction$0(RebuildInstanceOperation.java:18)
	... 23 more
```

**Comment by vania-pooh** [comment]
One more issue:
```
2016-12-04 16:12:17,831 [          pool-3-thread-2] ERROR org.meridor.perspective.digitalocean.BaseInstanceOperation   - Failed to rebuild instance test-instance-blr (d1dc79b6-e553-32ce-91ab-b0af6caca581)
java.lang.RuntimeException: com.myjeeva.digitalocean.exception.DigitalOceanException: The resource you were accessing could not be found.
	at org.meridor.perspective.digitalocean.RebuildInstanceOperation.lambda$getAction$2(RebuildInstanceOperation.java:21)
	at org.meridor.perspective.digitalocean.RebuildInstanceOperation$$Lambda$69/1713220971.apply(Unknown Source)
	at org.meridor.perspective.digitalocean.BaseInstanceOperation.perform(BaseInstanceOperation.java:30)
	at org.meridor.perspective.worker.operation.impl.OperationProcessorImpl.supply(OperationProcessorImpl.java:58)
	at org.meridor.perspective.worker.processor.InstanceFSM.onInstanceRebuilding(InstanceFSM.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.callMethod(BestMatchedAnnotatedMethodCaller.java:100)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.findSuitableMethodAndCall(BestMatchedAnnotatedMethodCaller.java:70)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.call(BestMatchedAnnotatedMethodCaller.java:51)
	at ru.yandex.qatools.fsm.impl.BestMatchedAnnotatedMethodCaller.call(BestMatchedAnnotatedMethodCaller.java:31)
	at ru.yandex.qatools.fsm.impl.YatomataImpl.fire(YatomataImpl.java:115)
	at org.meridor.perspective.worker.processor.InstancesProcessor.processInstances(InstancesProcessor.java:57)
	at org.meridor.perspective.worker.processor.InstancesProcessor.process(InstancesProcessor.java:37)
	at org.meridor.perspective.worker.processor.WorkerDispatcher.dispatch(WorkerDispatcher.java:45)
	at org.meridor.perspective.backend.messaging.impl.BaseConsumer.lambda$getRunnable$0(BaseConsumer.java:69)
	at org.meridor.perspective.backend.messaging.impl.BaseConsumer$$Lambda$21/1848886161.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.myjeeva.digitalocean.exception.DigitalOceanException: The resource you were accessing could not be found.
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.evaluateResponse(DigitalOceanClient.java:1377)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.executeHttpRequest(DigitalOceanClient.java:1322)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.doPost(DigitalOceanClient.java:1284)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:1241)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.rebuildDroplet(DigitalOceanClient.java:473)
	at org.meridor.perspective.digitalocean.ApiProviderImpl$ApiImpl.rebuildDroplet(ApiProviderImpl.java:131)
	at org.meridor.perspective.digitalocean.RebuildInstanceOperation.lambda$getAction$2(RebuildInstanceOperation.java:18)
	... 23 more

```

**Comment by vania-pooh** [comment]
Fixed in https://github.com/meridor/perspective-backend/commit/5f0d9439829e073cc884171ce56d5cb16998046a.
