### ISSUE TITLE
Current thread is not owner of the lock

### ISSUE THREAD

**Issue by vania-pooh** [meridor/perspective-backend#49]
```
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> <not-locked>
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.ensureUnlocked(UnlockOperation.java:71)
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:65)
    at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:57)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:380)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:342)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:247)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:231)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:198)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:168)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:51)
    at com.hazelcast.client.impl.client.PartitionClientRequest.process(PartitionClientRequest.java:58)
    at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:463)
    at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:379)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:100)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:130)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:120)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76)
```

This is shown in storage log.

**Comment by vania-pooh** [comment]
Upgraded to Hazelcast 3.5.4 in https://github.com/meridor/perspective-backend/commit/fb80460e4ffc3837ea6669c7b509ef5e53bec5f5. Will reopen in next milestone if still reproduces.
